### ISSUE TITLE
Forklare hvordan man trykker når man oppretter arrangement

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMnettverket#48]
Når man velger på linje 1, må den automatisk velge noe i linje 2.
For fylker bør den velge videresending, for alle andre bør den velge "åpen påmelding"

**Comment by christianhva** [comment]
Won’t Fix #48 ❌På grunn av flyten i valgene er det ikke mulig å gjøre det enklere å forstå for brukeren uten å redesigne flyten. 

Når øverste lag er valg vil det være naturlig å sette fokus på lag nr to og vise liste med navn, dato og lenke. Hvis man gjør dette vil det være mer utydelig at man kan velge andre alternativer i lag en og lag to. 

Legger ved fil for å vise hvordan det blir vanskelig å velge. 

<img width="1237" alt="Skjermbilde 2020-01-09 kl  19 11 46" src="https://user-images.githubusercontent.com/17315368/72093022-e9e95680-3313-11ea-9ef5-74abe1087636.png">

*mic drop*
