### ISSUE TITLE
Forklar videresending / åpen påmelding bedre

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMnettverket#64]
Ved oppretting av arrangement, er det behov for å forklare valgene enda bedre.

@tomandreaskristensen var inne på en formulering om "Jeg må putte de inn, vs de kan melde seg på".

**Comment by tomandreaskristensen** [comment]
Usikker på om det er lov å bruke frasen "å putte inn"... 

Men for å hekte meg på her, er det snakk om forskjellen mellom deltakerne som selv ønsker å melde seg på og deltakerne som må legges inn i systemet fordi ikke får til/ikke ser verdien av å melde seg på selv...?

**Comment by mariusmandal** [comment]
Haha, godt poeng @tomandreaskristensen. Det er ikke at vi skal gå for den formuleringen, men det sier jo noe om mindset: deltakerne melder seg på selv i motsetning til her må jeg melde de inn. Men det er jo også litt på siden av hvordan det faktisk fungerer der.. For ved videresending er det andre arrangement (evt dine arrangement) som videresender til deg.
Kommer tilbake til denne i slack når vi nærmer oss å kunne ta tak i den :) 

Forøvrig relatert til #62

**Comment by mariusmandal** [comment]
Flyttet inn til feature request system
